In [7]:
import googlemaps
import numpy as np
import heapq

# Set your Google Maps API key
API_KEY = 'AIzaSyCKj0YV5BGVpIYtOvDesOQE4rfboiosggQ'
gmaps = googlemaps.Client(key=API_KEY)
print(gmaps)

In [37]:
from googlemaps.exceptions import HTTPError
# Define locations (place IDs or addresses) and stay times (in hours)
locations = ['ChIJQ9yCmWtZ4joRNu1evW41NTo', 'ChIJC46ViHtZ4joRCya8Jp8IxcE', 'ChIJTXbn3s9b4joRxbASabb7l98', 'ChIJseUqHGtZ4joRgteF9GKSLoc']
stay_times = [2, 1, 3, 2]  # Example stay times in hours

# Initialize distance matrix and neighbors
distance_matrix = np.zeros((len(locations), len(locations)))
neighbors = {i: [] for i in range(len(locations))}

print(distance_matrix)

# Function to get distance and duration between two locations
def get_distance_duration(origin, destination):
    result = gmaps.distance_matrix(origins=f'place_id:{origin}', destinations=f'place_id:{destination}')
    print(result)
    print(origin)
    print(destination)
    return result['rows'][0]['elements'][0]['distance']['value'], result['rows'][0]['elements'][0]['duration']['value']

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:
# Populate distance matrix and neighbors
for i in range(len(locations)):
    for j in range(len(locations)):
        if i != j:
            origin = locations[i]
            destination = locations[j]
            distance, duration = get_distance_duration(origin, destination)
            distance_matrix[i][j] = duration
            neighbors[i].append(j)

{'destination_addresses': ['7 Independence Ave, Colombo 00700, Sri Lanka'], 'origin_addresses': ['61 Sri Jinarathana Rd, Colombo 00200, Sri Lanka'], 'rows': [{'elements': [{'distance': {'text': '2.4 km', 'value': 2427}, 'duration': {'text': '6 mins', 'value': 349}, 'status': 'OK'}]}], 'status': 'OK'}
ChIJQ9yCmWtZ4joRNu1evW41NTo
ChIJC46ViHtZ4joRCya8Jp8IxcE
{'destination_addresses': ['1A Centre Road, Colombo 00200, Sri Lanka'], 'origin_addresses': ['61 Sri Jinarathana Rd, Colombo 00200, Sri Lanka'], 'rows': [{'elements': [{'distance': {'text': '3.3 km', 'value': 3305}, 'duration': {'text': '10 mins', 'value': 602}, 'status': 'OK'}]}], 'status': 'OK'}
ChIJQ9yCmWtZ4joRNu1evW41NTo
ChIJTXbn3s9b4joRxbASabb7l98
{'destination_addresses': ['137 Sir James Pieris Mawatha, Colombo 00200, Sri Lanka'], 'origin_addresses': ['61 Sri Jinarathana Rd, Colombo 00200, Sri Lanka'], 'rows': [{'elements': [{'distance': {'text': '0.3 km', 'value': 251}, 'duration': {'text': '1 min', 'value': 45}, 'status': 'OK'

In [39]:
# Define a class to represent a state in the search space
class State:
    def __init__(self, location, time, path, cost):
        self.location = location
        self.time = time
        self.path = path
        self.cost = cost

    def __lt__(self, other):
        return self.cost < other.cost

In [40]:
# A* algorithm for route optimization
def a_star(start_location, start_time, end_time):
    # Priority queue for states to explore
    open_set = [State(start_location, start_time, [start_location], 0)]

    # Set to track visited states
    closed_set = set()

    while open_set:
        # Get the state with the lowest cost estimate
        current_state = heapq.heappop(open_set)

        # Check if the goal is reached
        if current_state.location == end_location and current_state.time <= end_time:
            return current_state.path

        # Generate successor states
        successors = generate_successors(current_state, end_time)

        for successor in successors:
            # Check if the successor state is not in the closed set
            if successor.location not in closed_set:
                # Add the successor state to the open set
                heapq.heappush(open_set, successor)

        # Add the current state to the closed set
        closed_set.add(current_state.location)

    return None  # No valid route found


In [41]:
# Function to generate successor states
def generate_successors(current_state, end_time):
    successors = []

    for neighbor in neighbors[current_state.location]:
        # Calculate travel time and new arrival time
        travel_time = distance_matrix[current_state.location][neighbor]
        new_time = current_state.time + travel_time + stay_times[neighbor]

        # Check if the new time is within the time window
        if new_time <= end_time:
            new_path = current_state.path + [neighbor]
            new_cost = current_state.cost + travel_time

            # Heuristic estimate (you can adjust this based on your specific requirements)
            heuristic_estimate = get_heuristic_estimate(neighbor, end_location)

            # A* cost function: cost-so-far + heuristic estimate
            total_cost = new_cost + heuristic_estimate

            # Create a new successor state
            successor = State(neighbor, new_time, new_path, total_cost)
            successors.append(successor)

    return successors

In [42]:
# Function to get a heuristic estimate (you can adjust this based on your specific requirements)
def get_heuristic_estimate(location, goal_location):
    return distance_matrix[location][goal_location]

In [44]:
# Example usage
start_location = 3  # Starting location index
end_location = 1    # Ending location index
start_time = 9      # Starting time
end_time = 18       # Ending time

optimized_route = a_star(start_location, start_time, end_time)
print("Optimized Route:", optimized_route)

Optimized Route: None
